### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jojomojojojomojo** [hectorgimenez/koolo#125]
### Details

Hi, I am getting this when I try to run baal runs in companion mode
```
time=2024-04-02T23:38:20.956+03:00 level=INFO msg="Starting Game #0. Run list: Companion"
time=2024-04-02T23:38:20.956+03:00 level=INFO msg="Running: Companion"
time=2024-04-02T23:38:24.378+03:00 level=WARN msg="Game finished with errors, reason: fatal error detected, Koolo will try to exit game and create a new one: runtime error: invalid memory address or nil pointer dereference. Game total time: 3.39s"
```

In short, the second instance comes into play and immediately exists

```yml
companion:
  enabled: true
  leader: false
  leaderName: 'Set'
  attack: false
  gameNameTemplate: custom
  gamePassword: xxx
```

### Version

v0.4.0-beta4
